routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@home')->name('home');
//Route::get('home', 'IndexController@home')->name('home');
Route::resource('user','UserController');
Route::get('logout','LoginController@logout')->name('logout');
Route::get('login','LoginController@login')->name('login');
Route::post('login','LoginController@store')->name('login');

Route::get('confirmEmailToken/{token}','UserController@confirmEmailToken')->name('confirmEmailToken');

Route::get('follow/{user}','UserController@follow')->name('user.follow');
//找回密码
Route::get('FindPasswordEmail','PasswordController@email')->name('FindPasswordEmail');
Route::post('FindPasswordSend','PasswordController@send')->name('FindPasswordSend');
Route::get('FindPasswordEdit/{token}','PasswordController@edit')->name('FindPasswordEdit');
Route::post('FindPasswordUpdate','PasswordController@update')->name('FindPasswordUpdate');
//博客
Route::resource('blog','BlogController');

Route::get('follower/{user}','FollowController@follower')->name('follow');
Route::get('following/{user}','FollowController@following')->name('following');

resources/views/follow.blade.php
@extends('layouts.default')
@section('content')
    <div class="card">
        <div class="card-header">
            <h2>{{$title}}</h2>
        </div>
        <div class="card-body">
            <table class="table">
                @foreach($users as $user)
                    <tr>
                        <td><a href="{{route('user.show',$user)}}">{{$user->name}}</a></td>
                    </tr>
                @endforeach
            </table>
        </div>
        <div class="card-footer text-muted">
            {{$users->links()}}
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.default')
@section('content')
    @auth
        <form action="{{route('blog.store')}}" method="post">
            @csrf
            <div class="card">
                <div class="card-header">
                    发布博客
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="">内容</label>
                        <textarea class="form-control" name="content">{{old('content')}}</textarea>
                    </div>
                </div>
                <div class="card-footer text-muted">
                    <button type="submit" class="btn btn-success">发表</button>
                </div>
            </div>
        </form>
    @endauth
    {{--    博客列表--}}
    <div class="card mt-2">
        <div class="card-header">
            博客列表
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>内容</th>
                    <th>作者</th>
                </tr>
                </thead>
                <tbody>
                @foreach($blogs as $blog)
                    <tr>
                        <td>{{$blog->id}}</td>
                        <td>{{$blog->content}}</td>
                        <td>
                            <a href="{{route('user.show',$blog->user)}}">{{$blog->user->name}}</a>
                            @can('delete',$blog)
                                <form action="{{route('blog.destroy',$blog)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger btn-sm">删除</button>
                                </form>
                            @endcan
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div class="card-footer text-muted">
            {{$blogs->links()}}
        </div>
    </div>
@endsection

resources/views/login.blade.php
@extends('layouts.default')
@section('content')
    @include('layouts._errors')
    <form action="{{route('login')}}" method="post">
        @csrf
        <div class="card">
            <div class="card-header">
                用户登录
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label for="">邮箱</label>
                    <input type="text" class="form-control" name="email" value="{{old('email')}}">
                </div>
                <div class="form-group">
                    <label for="">密码</label>
                    <input type="password" class="form-control" name="password">
                </div>
                <div class="form-group">
                    <label for=""></label>
                    <a href="{{route('FindPasswordEmail')}}">找回密码</a>
                </div>
            </div>
            <div class="card-footer text-muted">
                <button type="submit" class="btn btn-success">登录</button>
            </div>
        </div>
    </form>
@endsection