routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@home')->name('home');
//Route::get('home', 'IndexController@home')->name('home');
Route::resource('user','UserController');
Route::get('logout','LoginController@logout')->name('logout');
Route::get('login','LoginController@login')->name('login');
Route::post('login','LoginController@store')->name('login');

Route::get('confirmEmailToken/{token}','UserController@confirmEmailToken')->name('confirmEmailToken');

Route::get('follow/{user}','UserController@follow')->name('user.follow');
//找回密码
Route::get('FindPasswordEmail','PasswordController@email')->name('FindPasswordEmail');
Route::post('FindPasswordSend','PasswordController@send')->name('FindPasswordSend');
Route::get('FindPasswordEdit/{token}','PasswordController@edit')->name('FindPasswordEdit');
Route::post('FindPasswordUpdate','PasswordController@update')->name('FindPasswordUpdate');
//博客
Route::resource('blog','BlogController');

Route::get('follower/{user}','FollowController@follower')->name('follow');
Route::get('following/{user}','FollowController@following')->name('following');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function blogs(){
        return $this->hasMany(Blog::class);
    }

    //粉丝，查找我的粉丝
    public function follower(){
        return $this->belongsToMany(User::class,'follows','user_id','follower');
    }
    //被关注着，粉丝是主角（获取所有关注）
    public function following(){
        return $this->belongsToMany(User::class,'follows','follower','user_id');
    }

    //是否关注了当前用户（指定用户是否是粉丝）
    public function isFollow($uid){
        return $this->follower()->where('follower',$uid)->first();
    }

    //关注或取消关注
    public function followToggle($ids){
        $ids = is_array($ids)?:[$ids];
        return $this->follower()->withTimestamps()->toggle($ids);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Mail\RegMail;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth',[
            'except'=>['index','show','create','store','confirmEmailToken']//排除方法
        ]);
        $this->middleware('guest',[
            'only'=>['create','store']//只允许游客使用这两个方法
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::paginate(10);
        return view('user.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request->all());
        $data = $this->validate($request,[
            'name'=>'required|min:3',
            'email'=>'required|unique:users|email',
            'password'=>'required|min:5|confirmed'
        ]);
        $data['password'] = bcrypt($data['password']);
        //添加用户
        $user = User::create($data);
        //自动登录
        //Auth::attempt(['email'=>$request->email,'password'=>$request->password]);
        //发送邮件
        \Mail::to($user)->send(new RegMail($user));
        session()->flash('success','请查看邮箱，完成注册验证');
        return redirect()->route('home');
    }
    //关注或取消关注
    public function follow(User $user){
        $user->followToggle(Auth::user()->id);
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $blogs = $user->blogs()->paginate(5);
        if(Auth::check()){
            $followTitle = $user->isFollow(Auth::user()->id)?'取消关注':'关注';
        }
        return view('user.show',compact('user','blogs','followTitle'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $this->authorize('update',$user);
        return view('user.edit',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $data = $this->validate($request,[
            'name'=>'required|min:3',
            'password'=>'nullable|min:5|confirmed'//nullabel：如果有则验证后面两个，如果没有就不验证，因为修改用户资料时候密码可能不用修改，这个和required冲突
        ]);
        $user->name = $request->name;
        if($request->password){
            $user->password = bcrypt($request->password);
        }
        $user->save();
        session()->flash('success','用户资料修改成功');
        return redirect()->route('user.show',$user);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $this->authorize('delete',$user);
        $user->delete();
        session()->flash('success','删除成功');
        return redirect()->route('user.index');
    }
    //邮箱注册验证
    public function confirmEmailToken($token){
        $user = User::where('email_token',$token)->first();
        if($user){
            $user->email_active = true;
            $user->save();
            session()->flash('验证成功');
            Auth::login($user);
            return redirect('/');
        }
        //\Mail::to($user)->send(new RegMail($user));
        session()->flash('danger','邮箱验证失败');
        return redirect('/');
    }
}

resources/views/user/create.blade.php
@extends('layouts.default')
@section('content')
    @include('layouts._errors')
    <form action="{{route('user.store')}}" method="post">
        @csrf
        <div class="card">
            <div class="card-header">
                用户注册
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label for="">昵称</label>
                    <input type="text" class="form-control" name="name" value="{{old('name')}}">
                </div>
                <div class="form-group">
                    <label for="">邮箱</label>
                    <input type="text" class="form-control" name="email" value="{{old('email')}}">
                </div>
                <div class="form-group">
                    <label for="">密码</label>
                    <input type="password" class="form-control" name="password">
                </div>
                <div class="form-group">
                    <label for="">确认密码</label>
                    <input type="password" class="form-control" name="password_confirmation">
                </div>
            </div>
            <div class="card-footer text-muted">
                <button type="submit" class="btn btn-success">注册</button>
            </div>
        </div>
    </form>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.default')
@section('content')
    <form action="{{route('user.update',$user)}}" method="post">
        @csrf
        @method('PUT')
        <div class="card">
            <div class="card-header">
                修改资料
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label for="">昵称</label>
                    <input type="text" class="form-control" name="name" value="{{$user->name}}">
                </div>
                <div class="form-group">
                    <label for="">邮箱</label>
                    <input type="text" class="form-control" name="email" value="{{$user->email}}" disabled>
                </div>
                <div class="form-group">
                    <label for="">密码</label>
                    <input type="password" class="form-control" name="password" placeholder="为空则默认不修改密码">
                </div>
                <div class="form-group">
                    <label for="">确认密码</label>
                    <input type="password" class="form-control" name="password_confirmation">
                </div>
            </div>
            <div class="card-footer text-muted">
                <button type="submit" class="btn btn-success">确定修改</button>
            </div>
        </div>
    </form>
@endsection

resources/views/user/index.blade.php
@extends('layouts.default')
@section('content')
    <div class="card">
        <div class="card-header">
            用户列表
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th>编号</th>
                    <th>昵称</th>
                    <th width="100">操作</th>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                    <tr>
                        <td scope="row">{{$user->id}}</td>
                        <td>{{$user->name}}</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Basic example">
                                @can('delete',$user)
                                    <form action="{{route('user.destroy',$user)}}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">删除</button>
                                    </form>
                                @endcan
                                @can('update',$user)
                                    <a href="{{route('user.edit',$user)}}" class="btn btn-info">修改</a>
                                @endcan
                                <a href="{{route('user.show',$user)}}" class="btn btn-secondary">查看</a>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div class="card-footer text-muted">
            {{$users->links()}}
        </div>
    </div>
@endsection

resources/views/user/show.blade.php
@extends('layouts.default')
@section('content')

    <div class="card">
        <div class="card-header">
            <h1 class="text-center">{{$user->name}}</h1>
            <div class="text-center">
                <a href="{{route('follow',$user)}}" class="btn btn-info">粉丝：{{$user->follower()->count()}}</a>
                <a href="{{route('following',$user)}}" class="btn btn-info">关注数：{{$user->following()->count()}}</a>
                @auth
                    <a href="{{route('user.follow',$user)}}" class="btn btn-success">{{$followTitle}}</a>
                @endauth
            </div>
        </div>
        <div class="card-body">
            <table class="table">
                <tbody>
                @foreach($blogs as $blog)
                    <tr>
                        <td>{{$blog->id}}</td>
                        <td>{{$blog->content}}</td>
                        <td>
                            @can('delete',$blog)
                                <form action="{{route('blog.destroy',$blog)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger btn-sm">删除</button>
                                </form>
                            @endcan
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div class="card-footer text-muted">
            {{$blogs->links()}}
        </div>
    </div>
@endsection