routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@home')->name('home');
//Route::get('home', 'IndexController@home')->name('home');
Route::resource('user','UserController');
Route::get('logout','LoginController@logout')->name('logout');
Route::get('login','LoginController@login')->name('login');
Route::post('login','LoginController@store')->name('login');

Route::get('confirmEmailToken/{token}','UserController@confirmEmailToken')->name('confirmEmailToken');

Route::get('follow/{user}','UserController@follow')->name('user.follow');
//找回密码
Route::get('FindPasswordEmail','PasswordController@email')->name('FindPasswordEmail');
Route::post('FindPasswordSend','PasswordController@send')->name('FindPasswordSend');
Route::get('FindPasswordEdit/{token}','PasswordController@edit')->name('FindPasswordEdit');
Route::post('FindPasswordUpdate','PasswordController@update')->name('FindPasswordUpdate');
//博客
Route::resource('blog','BlogController');

Route::get('follower/{user}','FollowController@follower')->name('follow');
Route::get('following/{user}','FollowController@following')->name('following');

resources/views/layouts/_errors.blade.php
@if(count($errors)>0)
    <div class="alert alert-warning" role="alert">
    @foreach($errors->all() as $error)
            <li>{{$error}}</li>
    @endforeach
    </div>
@endif

resources/views/layouts/_message.blade.php
@foreach(['success','danger'] as $t)
    @if(session()->has($t))
        <div class="alert alert-{{$t}}" role="alert">
            <strong>{{session()->get($t)}}</strong>
        </div>
    @endif
@endforeach

resources/views/layouts/default.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/css/app.css">
    <title>博客系统</title>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">首页</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{route('user.index')}}">用户列表</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                @auth
                    <a href="{{route('user.show',auth()->user())}}" class="btn btn-dark my-2 my-sm-0 mr-2">空间</a>
                    <a href="{{route('user.edit',auth()->user())}}" class="btn btn-info my-2 my-sm-0 mr-2">修改</a>
                    <a href="{{route('logout')}}" class="btn btn-danger my-2 my-sm-0 mr-2">退出</a>
                @else
                    <a href="{{route('user.create')}}" class="btn btn-danger my-2 my-sm-0 mr-2">注册</a>
                    <a href="{{route('login')}}" class="btn btn-success my-2 my-sm-0">登录</a>
                @endauth

            </form>
        </div>
    </nav>
    @include('layouts._errors')
    @include('layouts._message')
    @yield('content')
</div>
<script src="/js/app.js"></script>
</body>
</html>